version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pengaduan-app-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
    depends_on:
      - redis
    networks:
      - pengaduan-network
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: pengaduan-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - pengaduan-network



volumes:
  redis_data_dev:

networks:
  pengaduan-network:
    driver: bridge